{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyNtKbWFV+8IEfXUoOJFJoeX"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["<h1 align='center'>Assignment No 7</h1>"],"metadata":{"id":"32IRaPwLNY0B"}},{"cell_type":"markdown","source":["Q1 What is the purpose of the try statement?"],"metadata":{"id":"gN5WxJcaNgEf"}},{"cell_type":"markdown","source":["- When an error occurs, or exception as we call it, Python will normally stop and generate an error message.\n","\n","- These exceptions can be handled using the try statement:\n","\n","\n","```\n","try:\n","  print(x)\n","except:\n","  print(\"An exception occurred\")\n","```\n","\n","\n","\n"],"metadata":{"id":"h0C8WJSKNoeX"}},{"cell_type":"markdown","source":["Q2 What are the two most popular try statement variations?"],"metadata":{"id":"UQAWKyGJN50n"}},{"cell_type":"markdown","source":["- A try statement, often referred to as a try block, in fact consists of at least two parts: try and except.\n","\n","- The code we want to safeguard goes inside the try portion of the block. Afterwards, we define what happens when something goes wrong within the except.\n","\n","- In the example above, we use the catch-all value Exception to route any exception to this portion of the block. We also print a vague message. But what if we want the actual error message from Python?\n","\n","- You can define multiple except blocks within a try, specifying the exact type of exception that should be routed to each. Additionally, you can set the error message to a variable—e is common—so it can be used in your program."],"metadata":{"id":"L6IWyuM9N9P-"}},{"cell_type":"markdown","source":["Q3 What is the purpose of the raise statement?"],"metadata":{"id":"X_QieN_GOQde"}},{"cell_type":"markdown","source":["- The raise keyword is used to raise an exception.\n","\n","- You can define what kind of error to raise, and the text to print to the user.\n","\n","\n","\n","```\n","x = \"hello\"\n","\n","if not type(x) is int:\n","  raise TypeError(\"Only integers are allowed\")\n","```\n","\n"],"metadata":{"id":"XUJeUlHZOT23"}},{"cell_type":"markdown","source":["Q4 What does the assert statement do, and what other statement is it like?"],"metadata":{"id":"xeEF4BCWOkme"}},{"cell_type":"markdown","source":["- The assert keyword is used when debugging code.\n","\n","- The assert keyword lets you test if a condition in your code returns True, if not, the program will raise an AssertionError.\n","\n","- You can write a message to be written if the code returns False, check the example below\n","\n","\n","\n","```\n","x = \"hello\"\n","\n","#if condition returns False, AssertionError is raised:\n","assert x == \"goodbye\", \"x should be 'hello'\"\n","```\n","\n"],"metadata":{"id":"EkYNE-wZOo6G"}},{"cell_type":"markdown","source":["Q5 What is the purpose of the with/as argument, and what other statement is it like?"],"metadata":{"id":"AF2qnnrHO4Z3"}},{"cell_type":"markdown","source":["- he with statement is a replacement for commonly used try/finally error-handling statements. A common example of using the with statement is opening a file. To open and write to a file in Python, you can use the with statement as follows: with open(\"example.txt\",'r')\n","\n","\n","\n","```\n","with open(\"example.txt\", \"w\") as file:\n","    file.write(\"Hello World!\")\n","```\n","\n"],"metadata":{"id":"KzJ-WWwBO75m"}}]}