{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyO4XVSKiU1bSPI2mQjomXBw"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["<h1 align='center'>Assignment No 8</h1>"],"metadata":{"id":"Cto5uefSPsfg"}},{"cell_type":"markdown","source":["Q1 What are the two latest user-defined exception constraints in Python 3.X?"],"metadata":{"id":"gn_rhzAlPy1-"}},{"cell_type":"markdown","source":["- Python detects all the critical errors that occur during Compile-time and Runtime. It stops the program's execution if the error occurs and raises an exception. Some commonly raised Exceptions are ArithmeticError, AttributeError, ImportError, IOError, FileNotFoundError, etc.\n","\n","- Sometimes we must enforce constraints on the values that specific program variables can take or save the program from running into an undesired state. In such situations, Python allows programmers to create User-defined Exceptions. To create a User-defined Exception, we need to create a class directly or indirectly derived from the built-in Exception class."],"metadata":{"id":"fs-5RdHpQR14"}},{"cell_type":"markdown","source":["Q2 How are class-based exceptions that have been raised matched to handlers?"],"metadata":{"id":"FeSqCszEQcZQ"}},{"cell_type":"markdown","source":["- User-defined Python exceptions can be either strings or Python classes. Since classes have many nice properties when used as exceptions, it is desirable to migrate to a situation where classes are used exclusively. Prior to Python 1.5 alpha 4, Python's standard exceptions (IOError, TypeError, etc.) were defined as strings. Changing these to classes posed some particularly nasty backward compatibility problems.\n","\n","- In Python versions 1.5 and later, the standard exceptions are Python classes, and a few new standard exceptions have been added. The obsolete AccessError exception has been deleted. Because it is possible (although unlikely) that this change broke existing code, the Python interpreter can be invoked the command line option -X to disable this feature, and use string exceptions like before. This option is a temporary measure - eventually the string-based standard exceptions will be removed from the language altogether. It hasn't been decided whether user-defined string exceptions will be allowed in Python 2.0."],"metadata":{"id":"9JSXaZrWQt1f"}},{"cell_type":"markdown","source":["Q3 Describe two methods for attaching context information to exception artefacts."],"metadata":{"id":"PaVQecrRQysX"}},{"cell_type":"markdown","source":["- There might arise a situation where there is a need for additional information from an exception raised by Python. \n","Python has two types of exceptions namely, Built-In Exceptions and User-Defined Exceptions.\n","- Why use Argument in Exceptions? \n","- Using arguments for Exceptions in Python is useful for the following reasons: \n","\n","- It can be used to gain additional information about the error encountered.\n"," \n","- As contents of an Argument can vary depending upon different types of Exceptions in Python, Variables can be supplied to the Exceptions to capture the essence of the encountered errors. Same error can occur of different causes, Arguments helps us identify the specific cause for an error using the except clause.\n"," \n","- It can also be used to trap multiple exceptions, by using a variable to follow the tuple of Exceptions. "],"metadata":{"id":"MK2EVjrZRBAd"}},{"cell_type":"markdown","source":["Q4 Describe two methods for specifying the text of an exception object&#39;s error message."],"metadata":{"id":"L5aa5RnyRIbO"}},{"cell_type":"markdown","source":["- Even if a statement or expression is syntactically correct, it may cause an error when an attempt is made to execute it. Errors detected during execution are called exceptions and are not unconditionally fatal: you will soon learn how to handle them in Python programs. Most exceptions are not handled by programs, however, and result in error messages as shown here:\n","- The preceding part of the error message shows the context where the exception occurred, in the form of a stack traceback. In general it contains a stack traceback listing source lines; however, it will not display lines read from standard input."],"metadata":{"id":"vKtN2sDERbyG"}},{"cell_type":"markdown","source":["Q5 Why do you no longer use string-based exceptions?"],"metadata":{"id":"GYSqc7vDRhgn"}},{"cell_type":"markdown","source":["- User-defined Python exceptions can be either strings or Python classes. Since classes have many nice properties when used as exceptions, it is desirable to migrate to a situation where classes are used exclusively. Prior to Python 1.5 alpha 4, Python's standard exceptions (IOError, TypeError, etc.) were defined as strings. Changing these to classes posed some particularly nasty backward compatibility problems."],"metadata":{"id":"Ap6_tLyeRktP"}}]}