{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyMj9CSDmjaxXrHWvcWke+Gm"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["<h1 align='center'>Assignment No 6</h1>\n"],"metadata":{"id":"xq1H7IsSJQFA"}},{"cell_type":"markdown","source":["Q1 Describe three applications for exception processing."],"metadata":{"id":"3kzihfLwJY9A"}},{"cell_type":"markdown","source":["- Raised when the specified key is not found in the dictionary. Raised when an identifier is not found in the local or global namespace. Raised when trying to access a local variable in a function or method but no value has been assigned to it. Base class for all exceptions that occur outside the Python environment.\n","- Division by Zero\n","- Accessing a file which does not exist.\n","- Addition of two incompatible types\n","- Trying to access a nonexistent index of a sequence\n","- Removing the table from the disconnected database server.\n","- ATM withdrawal of more than the available amount"],"metadata":{"id":"-MtVHF2SJdEv"}},{"cell_type":"markdown","source":["Q2 What happens if you don&#39;t do something extra to treat an exception?"],"metadata":{"id":"2ybVSudhKD5w"}},{"cell_type":"markdown","source":["- An exception is an issue (run time error) occurred during the execution of a program. For understanding purpose let us look at it in a different manner.\n","\n","- Generally, when you compile a program, if it gets compiled without a .class file will be created, this is the executable file in Java, and every time you execute this .class file it is supposed to run successfully executing each line in the program without any issues. But, in some exceptional cases, while executing the program, JVM encounters some ambiguous scenarios where it doesn’t know what to do."],"metadata":{"id":"CyWtraeQKFo6"}},{"cell_type":"markdown","source":["Q3 What are your options for recovering from an exception in your script?"],"metadata":{"id":"OL-Ig6WUKOor"}},{"cell_type":"markdown","source":["- You can also provide a generic except clause, which handles any exception. After the except clause(s), you can include an else-clause. The code in the else-block executes if the code in the try: block does not raise an exception. The else-block is a good place for code that does not need the try: block's protection."],"metadata":{"id":"VDqVn7QPKR7N"}},{"cell_type":"markdown","source":["Q4 Describe two methods for triggering exceptions in your script."],"metadata":{"id":"Rx2A0BtjKkm-"}},{"cell_type":"markdown","source":["- An unhandled exception displays an error message and the program suddenly crashes. To avoid such a scenario, there are two methods to handle Python exceptions:\n","\n","  1. Try – This method catches the exceptions raised by the program\n","  2. Raise – Triggers an exception manually using custom exceptions"],"metadata":{"id":"cbcki2n0Kn-G"}},{"cell_type":"markdown","source":["Q5 Identify two methods for specifying actions to be executed at termination time, regardless of\n","whether or not an exception exists."],"metadata":{"id":"g5zLVlW4Kz63"}},{"cell_type":"markdown","source":["- An exception is an error which happens at the time of execution of a program. However, while running a program, Python generates an exception that should be handled to avoid your program to crash. In Python language, exceptions trigger automatically on errors, or they can be triggered and intercepted by your code.\n","\n","- The exception indicates that, although the event can occur, this type of event happens infrequently. When the method is not able to handle the exception, it is thrown to its caller function. Eventually, when an exception is thrown out of the main function, the program is terminated abruptly."],"metadata":{"id":"_KviS82bK38w"}}]}